DEFAULT_CONCURRENT_LIMIT = 10
REPO_DISCOVERY_NO_REPO_RECHECK_DAYS = 7
# Backward-compatible alias for older imports/tests.
HF_EXACT_NO_REPO_RECHECK_DAYS = REPO_DISCOVERY_NO_REPO_RECHECK_DAYS
ARXIV_RELATION_NO_ARXIV_RECHECK_DAYS = 30
REPO_CACHE_DB_PATH = "cache.db"
CONTENT_CACHE_DIR = "cache"
OVERVIEW_CACHE_SUBDIR = "overview"
ABS_CACHE_SUBDIR = "abs"
ALPHAXIV_OVERVIEW_LANGUAGE = "en"
